
 
export const metadata = {
  title: {
    default : 'Basket' ,
    template : ''
  },
  description: "Generated by create next app",
};


export default function Layout({ children }) {
  const length = '1'
  return (
    <>
     {children}
    </> 
  );
}
