import { Poppins } from "next/font/google";
import "./globals.css";
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/themes/saga-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import Header from "./components/Header";
import Providers from "@/redux/provider";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body
          className={poppins.className}
          style={{ maxWidth: 1300, margin: "auto", }}
        >
        <Providers>
        <Header></Header>
          {children}
        </Providers>
        </body>
      </PrimeReactProvider>
    </html>
  );
}
